export const SET_LOADING = 'SET_LOADING';
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const SET_ERROR = 'SET_ERROR';

export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAILURE = 'FETCH_QUESTIONS_FAILURE';